### PR TITLE
Merge tag extract

### PR DESCRIPTION
**Pull request by chris-armstrong**
This is perhaps a more contentious change than the last PR (#1). It looks for merge tags from templating frameworks (I have a lot of source HTML with them inside from handlebars, liquidjs, etc).

Merge tags are typically delineated by braces (i.e. `{ .. }`). This change puts them inside script tags so they don't break the JSX that is generated.

### CODE REVIEW

**Comment by leodr** [comment]
What is the background on turning these Merge tags into script tags? Do you script them to be replaced in a way? Otherwise I think comments would be better.

**Comment by chris-armstrong** [comment]
Yes, the intent is that these are code, and I want to preserve them as such in the DOM so they can be replaced downstream  - this is harder to do with comments. Script tags with unknown mime types [are treated as data blocks by the browser and are ignored](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type).

**Comment by leodr** [comment]
To me the <script> tag implies that some JS that runs in the browser will use it as data, which would not be the case if I understand your use-case.

Can't we rather do something like a comment with a special format, such as `{/* $merge-tag: ... */}`?

That way you could automate the replacement and also not have random unused <script> tags appear in your DOM.

**Comment by chris-armstrong** [comment]
Fair enough, I'll switch to a comment style for now, and if my use case requires them to be preserved, I'll look at making it customisable.

**Pull request merged**
